Added style to counter component
isdi-coders-202207-bcn-coding-adventure/adrian-armesto-front pull request #3
Opened 2022-08-22 14:20 UTC by AdrianArmestoMena

2022-08-22 14:43 UTC, luisdudamel requested changes

2022-08-22 14:43 UTC, luisdudamel commented on src/components/Counter/CounterStyle.tsx
> +  .counter__container {
Hola Adrian.
En styled components podemos nestear selectores. No es necesario escribir un selector que comienza igual varias veces.

2022-08-22 14:54 UTC, luisdudamel approved these changes
4. Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-23 10:52 UTC, merged

2022-08-24 15:42 UTC, Csarroca reviewed
Hola Adri, 

¿Porqué has puesto un span en la linea 8 del Counter.tsx en vez de un div?

Gracias por tus comentarios.

2022-08-24 15:45 UTC, AdrianArmestoMena commented
Dado que en ese caso no me importa si es inline o block. El div lo uso cuando tengo que darle un tamaño al elemento pero en este caso ya me venía bien que el tamaño se adaptara al contenido.

2022-08-24 17:53 UTC, mariogl commented
@AdrianArmestoMena ¿por qué se ve así?

<img width="540" alt="image" src="https://user-images.githubusercontent.com/724842/186489141-e3392ad1-ed89-4113-b504-741ca1ae943c.png">

2022-08-24 17:55 UTC, Csarroca commented
Lo dices por el gap?  Creo q lo baje haciendo pruebas y se quedo mal puesto.