Feature/function counter
isdi-coders-202207-bcn-coding-adventure/adrian-armesto-front pull request #4
Opened 2022-08-23 12:54 UTC by AdrianArmestoMena

2022-08-23 13:25 UTC, mariogl requested changes

2022-08-23 13:25 UTC, mariogl commented on src/data/targetDate.ts
> +const targetDate = "2022, 12, 24";
Esto no es una fecha.

2022-08-23 13:25 UTC, mariogl commented on src/store/hooks.ts
> +const useCountdown = (targetDate: string) => {
Esto no es un hook de redux, ¿por qué está en este archivo?

2022-08-23 14:17 UTC, luisdudamel commented
5. Crea dos rutas: /home y /register. En /home debe verse el contador si aún no ha llegado la fecha clave, y si ya ha pasado debe verse un encabezado.

2022-08-23 14:17 UTC, merged

2022-08-24 15:33 UTC, Csarroca reviewed
Hola Adri,

buen código! Sólo un apunte: 

¿Sabías que si pones delante del new Date un + obtendrías el mismo resultado que con .getTime()? Por ejemplo refacotrizando las lineas 9 y 11 por : 

const limitDate = "2022-09-28T18:30:00+05:30";

    const difference = +new Date(limitDate) - +new Date();


De todas formas está estupendo.

2022-08-24 15:40 UTC, AdrianArmestoMena commented
@Csarroca Ok. Muchas gracias.