Tested counter component
isdi-coders-202207-bcn-coding-adventure/adrian-armesto-front pull request #6
Opened 2022-08-24 15:06 UTC by AdrianArmestoMena

2022-08-24 17:34 UTC, mariogl requested changes

2022-08-24 17:34 UTC, mariogl commented on src/components/Counter/Counter.tsx
> +  if (countDown > 0) {
¿El conditional rendering se escribe así?

2022-08-24 17:34 UTC, mariogl commented on src/components/Counter/Counter.test.tsx
> +describe("Given a counter component", () => {
En estos tests sólo estás comprobando que los textos aparecen, pero no compruebas nada más.

2022-08-24 17:58 UTC, AdrianArmestoMena commented on src/components/Counter/Counter.test.tsx
> +describe("Given a counter component", () => {
Estoy comprobando que los textos que aparecen son los que devuelve el custom hook. Al ser divs y spans me pareció una manera correcta de testearlo. ¿Quieres decir que tendría que cambiar o añadir suits al test del propio componente  o también testear el custom hook?

2022-08-24 18:00 UTC, AdrianArmestoMena commented on src/components/Counter/Counter.tsx
> +  if (countDown > 0) {
Entiendo que lo tendría que ubicar dentro del return. Me pongo a ello. Gracias

2022-08-25 11:26 UTC, facundotolosa requested changes

2022-08-25 11:26 UTC, facundotolosa commented on src/hooks/useCountdown.test.ts
> +describe("s", () => {
Adrian, ¿podrías explicarme por favor qué es lo que estás testeando? No entiendo los describe.

2022-08-25 11:26 UTC, facundotolosa commented on src/hooks/useCountdown.test.ts
> +    test("f", () => {
¿Qué es esto?

2022-08-25 11:27 UTC, AdrianArmestoMena commented on src/hooks/useCountdown.test.ts
> +describe("s", () => {
Ya lo solucioné. Disculpa!!

2022-08-25 11:27 UTC, AdrianArmestoMena commented on src/hooks/useCountdown.test.ts
> +    test("f", () => {
Ya lo solucioné. Disculpa!!

2022-08-25 11:28 UTC, facundotolosa commented on src/hooks/useCountdown.test.ts
> +    test("f", () => {
Muy bien, Adrián.

**FASE 7:** _En /register debe verse un encabezado si ya ha llegado la fecha clave, o redirigir a /home si aún no ha llegado._

2022-08-25 11:30 UTC, facundotolosa approved these changes

2022-08-25 11:32 UTC, facundotolosa approved these changes
**FASE 7**: _En /register debe verse un encabezado si ya ha llegado la fecha clave, o redirigir a /home si aún no ha llegado._

2022-08-25 11:35 UTC, merged

2022-08-25 11:42 UTC, mariogl commented on src/components/Counter/Counter.test.tsx
> +describe("Given a counter component", () => {
Quiero que testees los timers.